// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class HttpResponse {
  static encode(message: HttpResponse, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.status);

    writer.uint32(18);
    writer.bytes(message.body);

    const headers = message.headers;
    if (headers !== null) {
      const headersKeys = headers.keys();
      for (let i: i32 = 0; i < headersKeys.length; ++i) {
        const headersKey = headersKeys[i];
        writer.uint32(26);
        writer.fork();
        writer.uint32(10);
        writer.string(headersKey);
        writer.uint32(18);
        writer.string(headers.get(headersKey));
        writer.ldelim();
      }
    }

    writer.uint32(34);
    writer.string(message.error);
  }

  static decode(reader: Reader, length: i32): HttpResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new HttpResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.status = reader.int32();
          break;

        case 2:
          message.body = reader.bytes();
          break;

        case 3:
          let headersKey: string = "";
          let headersValue: string = "";
          let headersHasKey: bool = false;
          let headersHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                headersKey = reader.string();
                headersHasKey = true;
                break;

              case 2:
                headersValue = reader.string();
                headersHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.headers === null) {
              message.headers = new Map<string, string>();
            }
            const headers = message.headers;
            if (headers !== null && headersHasKey && headersHasValue) {
              headers.set(headersKey, headersValue);
            }
          }
          break;

        case 4:
          message.error = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  status: i32;
  body: Uint8Array;
  headers: Map<string, string>;
  error: string;

  constructor(
    status: i32 = 0,
    body: Uint8Array = new Uint8Array(0),
    headers: Map<string, string> = new Map(),
    error: string = ""
  ) {
    this.status = status;
    this.body = body;
    this.headers = headers;
    this.error = error;
  }
}
