# https://taskfile.dev

version: "3"

tasks:
  install-plugin-tools:
    cmds:
      - test -d ../go-plugin || ( cd .. && gh repo clone rraymondgh/go-plugin -- --branch dev_flag_flexibility --single-branch )
      - cd ../go-plugin && make build
      - mkdir -p bin
      - test -f bin/go-jsonschema || (wget -O go-jsonschema.tar.gz https://github.com/omissis/go-jsonschema/releases/download/v0.20.0/go-jsonschema_Linux_x86_64.tar.gz && tar -xvf go-jsonschema.tar.gz -C bin )
      - npm install --save as-proto
      - npm install --save-dev as-proto-gen
      - npm install --save-dev assemblyscript

  gen-plugin-schema:
    cmds:
      - bin/go-jsonschema --schema-root-type bitmagnet://plugins/manifest=PluginManifest -p schema --output schema/manifest_gen.go schema/manifest.schema.json

  gen-protoc-plugin:
    vars:
      GOPATH:
        sh: go env GOPATH
      PROTO:
        sh: find . -type f -name '*.proto' | xargs dirname
      GOPLUGINOPTS: "paths=source_relative,wasm_package=github.com/rraymondgh/plugins/wasm,goplugin_known_types=false"
    cmds:
      - for: { var: PROTO }
        cmd: protoc --go-plugin_out=. --go-plugin_opt={{ .GOPLUGINOPTS }} --plugin={{ .GOPATH }}/bin/protoc-gen-go-plugin {{ .ITEM }}/*.proto
      - protoc --plugin=protoc-gen-as=./node_modules/.bin/as-proto-gen --as_out=./assembly $(find . -name "*.proto")

  test:
    vars:
      ANON:
        sh: find . -type f -name 'radarr*.json'
    cmds:
      - for: { var: ANON }
        cmd: node_modules/.bin/tsx devutils/anonjson.ts --filename {{ .ITEM }}
      - ginkgo run -r -v
