// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class GetPluginConfigResponse {
  static encode(message: GetPluginConfigResponse, writer: Writer): void {
    const config = message.config;
    if (config !== null) {
      const configKeys = config.keys();
      for (let i: i32 = 0; i < configKeys.length; ++i) {
        const configKey = configKeys[i];
        writer.uint32(10);
        writer.fork();
        writer.uint32(10);
        writer.string(configKey);
        writer.uint32(18);
        writer.string(config.get(configKey));
        writer.ldelim();
      }
    }

    writer.uint32(16);
    writer.bool(message.loggingEnabled);

    writer.uint32(26);
    writer.string(message.pluginID);
  }

  static decode(reader: Reader, length: i32): GetPluginConfigResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetPluginConfigResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          let configKey: string = "";
          let configValue: string = "";
          let configHasKey: bool = false;
          let configHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                configKey = reader.string();
                configHasKey = true;
                break;

              case 2:
                configValue = reader.string();
                configHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.config === null) {
              message.config = new Map<string, string>();
            }
            const config = message.config;
            if (config !== null && configHasKey && configHasValue) {
              config.set(configKey, configValue);
            }
          }
          break;

        case 2:
          message.loggingEnabled = reader.bool();
          break;

        case 3:
          message.pluginID = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  config: Map<string, string>;
  loggingEnabled: bool;
  pluginID: string;

  constructor(
    config: Map<string, string> = new Map(),
    loggingEnabled: bool = false,
    pluginID: string = ""
  ) {
    this.config = config;
    this.loggingEnabled = loggingEnabled;
    this.pluginID = pluginID;
  }
}
