// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class GetIntResponse {
  static encode(message: GetIntResponse, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.exists);

    writer.uint32(16);
    writer.int64(message.value);
  }

  static decode(reader: Reader, length: i32): GetIntResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new GetIntResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.exists = reader.bool();
          break;

        case 2:
          message.value = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  exists: bool;
  value: i64;

  constructor(exists: bool = false, value: i64 = 0) {
    this.exists = exists;
    this.value = value;
  }
}
