// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class HasResponse {
  static encode(message: HasResponse, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.exists);
  }

  static decode(reader: Reader, length: i32): HasResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new HasResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.exists = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  exists: bool;

  constructor(exists: bool = false) {
    this.exists = exists;
  }
}
