// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class RemoveResponse {
  static encode(message: RemoveResponse, writer: Writer): void {
    writer.uint32(8);
    writer.bool(message.success);
  }

  static decode(reader: Reader, length: i32): RemoveResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RemoveResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.success = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  success: bool;

  constructor(success: bool = false) {
    this.success = success;
  }
}
