// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class SetBytesRequest {
  static encode(message: SetBytesRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.key);

    writer.uint32(18);
    writer.bytes(message.value);

    writer.uint32(24);
    writer.int64(message.ttlSeconds);
  }

  static decode(reader: Reader, length: i32): SetBytesRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SetBytesRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.key = reader.string();
          break;

        case 2:
          message.value = reader.bytes();
          break;

        case 3:
          message.ttlSeconds = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  key: string;
  value: Uint8Array;
  ttlSeconds: i64;

  constructor(
    key: string = "",
    value: Uint8Array = new Uint8Array(0),
    ttlSeconds: i64 = 0
  ) {
    this.key = key;
    this.value = value;
    this.ttlSeconds = ttlSeconds;
  }
}
