// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class SetStringRequest {
  static encode(message: SetStringRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.key);

    writer.uint32(18);
    writer.string(message.value);

    writer.uint32(24);
    writer.int64(message.ttlSeconds);
  }

  static decode(reader: Reader, length: i32): SetStringRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SetStringRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.key = reader.string();
          break;

        case 2:
          message.value = reader.string();
          break;

        case 3:
          message.ttlSeconds = reader.int64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  key: string;
  value: string;
  ttlSeconds: i64;

  constructor(key: string = "", value: string = "", ttlSeconds: i64 = 0) {
    this.key = key;
    this.value = value;
    this.ttlSeconds = ttlSeconds;
  }
}
