// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v6.30.2
// source: host/config/config.proto

package config

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPluginConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginConfigRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type GetPluginConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config         map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LoggingEnabled bool              `protobuf:"varint,2,opt,name=loggingEnabled,proto3" json:"loggingEnabled,omitempty"`
	PluginID       string            `protobuf:"bytes,3,opt,name=pluginID,proto3" json:"pluginID,omitempty"`
}

func (x *GetPluginConfigResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetPluginConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetPluginConfigResponse) GetLoggingEnabled() bool {
	if x != nil {
		return x.LoggingEnabled
	}
	return false
}

func (x *GetPluginConfigResponse) GetPluginID() string {
	if x != nil {
		return x.PluginID
	}
	return ""
}

// go:plugin type=host version=1
type ConfigService interface {
	GetPluginConfig(context.Context, *GetPluginConfigRequest) (*GetPluginConfigResponse, error)
}
