// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";
import { Timestamp } from "../google/protobuf/Timestamp";

export class HttpRequest {
  static encode(message: HttpRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.url);

    writer.uint32(18);
    writer.string(message.apikey);

    writer.uint32(26);
    writer.string(message.id);

    const requestedAt = message.requestedAt;
    if (requestedAt !== null) {
      writer.uint32(34);
      writer.fork();
      Timestamp.encode(requestedAt, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): HttpRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new HttpRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.url = reader.string();
          break;

        case 2:
          message.apikey = reader.string();
          break;

        case 3:
          message.id = reader.string();
          break;

        case 4:
          message.requestedAt = Timestamp.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  url: string;
  apikey: string;
  id: string;
  requestedAt: Timestamp | null;

  constructor(
    url: string = "",
    apikey: string = "",
    id: string = "",
    requestedAt: Timestamp | null = null
  ) {
    this.url = url;
    this.apikey = apikey;
    this.id = id;
    this.requestedAt = requestedAt;
  }
}
