// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class OnCloseRequest {
  static encode(message: OnCloseRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.connectionId);

    writer.uint32(16);
    writer.int32(message.code);

    writer.uint32(26);
    writer.string(message.reason);
  }

  static decode(reader: Reader, length: i32): OnCloseRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new OnCloseRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.connectionId = reader.string();
          break;

        case 2:
          message.code = reader.int32();
          break;

        case 3:
          message.reason = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  connectionId: string;
  code: i32;
  reason: string;

  constructor(connectionId: string = "", code: i32 = 0, reason: string = "") {
    this.connectionId = connectionId;
    this.code = code;
    this.reason = reason;
  }
}
