// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class CloseResponse {
  static encode(message: CloseResponse, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.error);
  }

  static decode(reader: Reader, length: i32): CloseResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CloseResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.error = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  error: string;

  constructor(error: string = "") {
    this.error = error;
  }
}
