// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class OnBinaryMessageRequest {
  static encode(message: OnBinaryMessageRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.connectionId);

    writer.uint32(18);
    writer.bytes(message.data);
  }

  static decode(reader: Reader, length: i32): OnBinaryMessageRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new OnBinaryMessageRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.connectionId = reader.string();
          break;

        case 2:
          message.data = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  connectionId: string;
  data: Uint8Array;

  constructor(connectionId: string = "", data: Uint8Array = new Uint8Array(0)) {
    this.connectionId = connectionId;
    this.data = data;
  }
}
