// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v6.30.2

import { Writer, Reader } from "as-proto/assembly";

export class OnTextMessageRequest {
  static encode(message: OnTextMessageRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.connectionId);

    writer.uint32(18);
    writer.string(message.message);
  }

  static decode(reader: Reader, length: i32): OnTextMessageRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new OnTextMessageRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.connectionId = reader.string();
          break;

        case 2:
          message.message = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  connectionId: string;
  message: string;

  constructor(connectionId: string = "", message: string = "") {
    this.connectionId = connectionId;
    this.message = message;
  }
}
