// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v6.30.2
// source: api/testapi/testapi.proto

package testapi

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *SimpleRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SimpleRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type SimpleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SimpleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HttpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url         string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Apikey      string                 `protobuf:"bytes,2,opt,name=apikey,proto3" json:"apikey,omitempty"`
	Id          string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	RequestedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=RequestedAt,proto3" json:"RequestedAt,omitempty"`
}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpRequest) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *HttpRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

// go:plugin type=plugin version=1
type IntegrationTest interface {
	ConfigTest(context.Context, *SimpleRequest) (*SimpleResponse, error)
	HTTPTest(context.Context, *HttpRequest) (*SimpleResponse, error)
}
