//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v6.30.2
// source: api/testapi/testapi.proto

package testapi

import (
	context "context"
	wasm "github.com/rraymondgh/plugins/wasm"
)

const IntegrationTestPluginAPIVersion = 1

//go:wasmexport integration_test_api_version
func _integration_test_api_version() uint64 {
	return IntegrationTestPluginAPIVersion
}

var integrationTest IntegrationTest

func RegisterIntegrationTest(p IntegrationTest) {
	integrationTest = p
}

//go:wasmexport integration_test_config_test
func _integration_test_config_test(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(SimpleRequest)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := integrationTest.ConfigTest(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//go:wasmexport integration_test_http_test
func _integration_test_http_test(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(HttpRequest)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := integrationTest.HTTPTest(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
